### ISSUE TITLE
Planificar as charlas

### ISSUE THREAD

**Issue by antonmry** [vigojug/vigojug#2]
**2017 - 29 de Marzo - 19:30**

- Make Java Great Again @tomasalmeida de @netcentric. **30 min.**
- "De Groovy... e Sancho Panza" @antonmry de @optaresolutions. **30 min.**

**2017 - 25 de Abril - 19:30**

- Reservada (presentación confirmada).
- "Introducción de Cassandra con Java" por Alejandro Moratinos de PDTE. **30 min.**

**2017 - 30 de Maio - 19:30**

- "Introducción a Scala" por @rubenrua "The optimizator" de Teltek Video Research. **30 min.**
- "Microservices con SpringBoot" @vfdiaz de @optaresolutions **30 min.**

**2017 - 27 de Xuño  - 19:30**

- "Carballo Chess Engine, C++ vs. Java" por @albertoruibal de @mobialia **30 min.**
- Charla / Java Puzzlers / Test / lightning talks ??

**2017 - 18 de Xullo/26 de Xullo - 19:30**

- Vacacións? Algo diferente? 
- Workshop?

**2017 Agosto**

- Vacacións

**2017 - 26 de Setembro - 19:30**

- "Soluciones in-memory: coherence" por Miguel García de @oracle
- Java Puzzlers / Test / lightning talks ??

**Comment by tomasalmeida** [comment]
movemos eso para la pagina?

**Comment by antonmry** [comment]
veña, non é tan doado de editar pero nos apañamos ben! :+1:
