### ISSUE TITLE
Subir "material publicitario" a un repo

### ISSUE THREAD

**Issue by tomasalmeida** [vigojug/vigojug#3]
Subir el logo y todo el material publicitario hecho en un repo con licencia Creative Commons

**Comment by antonmry** [comment]
Moi de acordo :+1:

Podemos usar este mesmo, ¿que che parece?

**Comment by tomasalmeida** [comment]
perfecto, voy haciendo con lo que tengo

**Comment by tomasalmeida** [comment]
Logo subido

**Comment by tomasalmeida** [comment]
@antonmry, subes el banner que hiciste y cerramos este issue?

**Comment by antonmry** [comment]
Done!!
