### ISSUE TITLE
Conseguir licencias de IntelliJ para sortear

### ISSUE THREAD

**Issue by tomasalmeida** [vigojug/vigojug#5]
(preguntar PHPVigo?)

**Comment by orestes** [comment]
Solo tenéis que rellenar esto https://www.jetbrains.com/support/community/#section=communities

**Comment by tomasalmeida** [comment]
guay, me asigno la tarea y lo relleno hoy, gracias @orestes

**Comment by tomasalmeida** [comment]
Rellenado!

**Comment by tomasalmeida** [comment]
las tenemos!
