### ISSUE TITLE
Meetup VigoJUG 1

### ISSUE THREAD

**Issue by antonmry** [vigojug/vigojug#6]
- [x] Confirmar ponentes
- [x] Confirmar local
- [x] Crear PR entrada na web
- [x] Aprobación e merge
- [x] Crear en meetup
- [x] Publicar en Twitter
- [x] Mandar correo recordatorio (3-4 días antes)
- [x] Confirmar que será grabado (david)
- [x] Re anunciar en twitter (1-2 días antes)
- [x] Preparar kahoot
- [x] Avisar o Porto Santo das cervezas
- [x] Preparar Challenge e publicarlo
- [x] Facer o meetup e gravar as charlas
- [x] Entregar la licencia
- [x] Subir slides e código a repo VigoJUG
     - [x] @antonmry
     - [x] @tomasalmeida (pendente revisión)
- [x] Reto ( @antonmry )
- [x] Publicar entrada resumo + videos + correo + recordatorio seguinte charla ( @antonmry )
- [x] Mandar a enquisa ( @tomasalmeida )
     - [x] Question about basic vs. advanced talks
     - [x] Question about reading club
     - [x] Question about JDK9 hack day (April 22) 
     - [x] Question about study group (Java 9, introduction, etc.)
     - [x] Question about workshop with kids (minecraft)
     - [x] Other

**Comment by tomasalmeida** [comment]
falta mi parte sobre el make java great again... Hasta viernes EOD lo pongo

**Comment by tomasalmeida** [comment]
all done.

**Comment by antonmry** [comment]
xenial :clap:
